[package]
name = "catnap"
description = "A trait-first Rust REST client inspired by Eclipse MicroProfile REST Client."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
http.workspace = true
percent-encoding.workspace = true
quick-xml = { workspace = true, optional = true }
reqwest.workspace = true
serde.workspace = true
serde_json = { workspace = true, optional = true }
tracing.workspace = true
url.workspace = true

catnap-macros = { path = "../catnap-macros" }

[features]
default = ["basic-auth", "json", "tls-rustls"]
basic-auth = []
json = ["dep:serde_json", "reqwest/json"]
tls-rustls = ["reqwest/rustls"]
xml = ["dep:quick-xml"]

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true

[[example]]
name = "httpbin_json"
path = "examples/httpbin_json.rs"

[[example]]
name = "httpbin_xml"
path = "examples/httpbin_xml.rs"
required-features = ["xml"]

[[example]]
name = "httpbin_status"
path = "examples/httpbin_status.rs"

[[example]]
name = "httpbin_basic_auth"
path = "examples/httpbin_basic_auth.rs"
required-features = ["basic-auth", "json"]
