[package]
name = "catnap"
description = "A trait-first Rust REST client inspired by Eclipse MicroProfile REST Client."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
http.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
url.workspace = true

catnap-macros = { path = "../catnap-macros" }

[dev-dependencies]
serde_json.workspace = true
tokio.workspace = true
